CREATE TABLE TB_STUDENT(
	STD_NO NUMBER PRIMARY KEY,
	STD_NAME VARCHAR2(20) NOT NULL,
	STD_AGE NUMBER NOT NULL,
	STD_GENDER CHAR(1),
	STD_SCORE CHAR(1) 
);

SELECT * FROM TB_STUDENT;

--제약조건 
ALTER TABLE TB_STUDENT
ADD CONSTRAINT CHECK_GENDER
CHECK(STD_GENDER IN ('M', 'F') );

--제약조건 
ALTER TABLE TB_STUDENT
ADD CONSTRAINT CHECK_SCORE
CHECK(STD_SCORE IN ('A', 'B', 'C', 'D', 'F') );

CREATE SEQUENCE SEQ_TODO_NO NOCACHE;


INSERT INTO TB_STUDENT
VALUES (SEQ_TODO_NO.NEXTVAL, '김길동', 20, 'M', 'A');


SELECT STD_NO,STD_NAME,STD_AGE,STD_GENDER,STD_SCORE
FROM TB_STUDENT;

INSERT INTO TB_STUDENT
VALUES(SEQ_TODO_NO.NEXTVAL,?,?,?)
